#!/bin/zsh

set -x

time \
./import-pdschurchoffice-to-sqlite3.pl \
    --pxview=/Users/jsquyres/bogus/bin/pxview \
    --pdsdata-dir=/Users/jsquyres/git/epiphany/extract-pds-churchoffice-data/data |& tee import.out
