name: Set Ecobee schedules

on:
  # This is just for debugging on the PR where we first commit the
  # Ecobee schedule code
  pull_request_target:
  schedule:
    - cron: "25,55 9-23 * * *"  # 5:25 AM to 9:55 PM EST

  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  set-ecobee-schedules:
    runs-on: ubuntu-24.04

    steps:
      - name: Just put something here
        run: echo Hello, world!
