name: Set Ecobee schedules

on:
  # This is just for debugging on the PR where we first commit the
  # Ecobee schedule code
  pull_request_target:
  schedule:
    - cron: "25,55 9-23 * * *"  # 5:25 AM to 9:55 PM EST

  # Allow manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  set-ecobee-schedules:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          echo Hello, world!

      - name: Save secrets to files
        run: |
          echo Hello, world!

      - name: Run the main.py script
        run: |
          echo Hello, world!
