name: Set Ecobee schedules

on:
  # This is just for debugging on the PR where we first commit the
  # Ecobee schedule code
  pull_request:
  schedule:
    # We really only need to run between 5:25am and 9:55pm
    # JMS: Is this UTC or US Eastern?
    - cron: "25,55 9-23 * * *"

  # Allows manual runs
  workflow_dispatch:

permissions:
  contents: read

jobs:
  set-ecobee-schedules:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r media/linux/ecobee-control/requirements.txt

      - name: Save secrets to files
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > ${GITHUB_WORKSPACE}/google-credentials.json
          echo '${{ secrets.TOKEN_JSON }}' > ${GITHUB_WORKSPACE}/token.json
          echo '${{ secrets.ECOBEE_CREDENTIALS }}' > ${GITHUB_WORKSPACE}/ecobee-credentials.json
          echo '${{ secrets.ECOBEE_ACCESS_TOKEN }}' > ${GITHUB_WORKSPACE}/ecobee-access-token.json
          echo '${{ secrets.ECOBEE_REFRESH_TOKEN }}' > ${GITHUB_WORKSPACE}/ecobee-refresh-token.json

      - name: Run the main.py script
        env:
          # JMS Looks like the code refers to these as env variables
          # JMS Need to consolidate: all env variables or all files
          ECOBEE_ACCESS_TOKEN: ${{ secrets.ECOBEE_ACCESS_TOKEN }}
          ECOBEE_REFRESH_TOKEN: ${{ secrets.ECOBEE_REFRESH_TOKEN }}
        run: |
          cd media/linux/ecobee-control
          python3 ./main.py \
              --config google_calendar/config.json \
              --google-credentials ${GITHUB_WORKSPACE}/google-credentials.json \
              --token-json ${GITHUB_WORKSPACE}/token.json
